local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 2
  publish_frequency: 2
  transform_tolerance: 2

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.1
  
